fixing a syntax error
I get a syntax error warning when running this module under Ubuntu. This is caused by a missing comma in the Ubuntu manifest.

```
Error: Syntax error at 'notify'; expected '}' at /etc/puppet/modules/datadog/manifests/ubuntu.pp:20 on node local
```